<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Pairs each Lesson 1:1 with the ClassSession it was generated for — Lessons are
 * now generated by TimetableService alongside their session instead of by a
 * separate ClassSchedule-driven bulk pass (timetable-management.md, lesson.md §7).
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::table('edu_lessons', function (Blueprint $table) {
            $table->foreignId('session_id')->nullable()->after('class_room_id')
                ->constrained('edu_sessions')->nullOnDelete();
        });
    }

    public function down(): void
    {
        Schema::table('edu_lessons', function (Blueprint $table) {
            $table->dropConstrainedForeignId('session_id');
        });
    }
};
